[package]
name = "dmt"
description = "'7 Days Modding Tool' - A command line tool for managing 7 Days to Die Modlet builds"
authors = ["Donovan C. Young"]
edition = "2021"
version = "0.2.0"
rust-version = "1.74"
readme = "README.md"
repository = "https://github.com/DonovanMods/7dmt"
documentation = "https://docs.rs/7dmt"
license = "MIT OR Apache-2.0"
keywords = ["7dtd", "game-dev", "modinfo", "xml", "modding"]
categories = [
  "development-tools",
  "game-development",
  "parser-implementations",
  "command-line-utilities",
]
exclude = [".trunk/*", "tests/*", "src/tests/*"]

[[bin]]
name = "7dmt"
path = "src/main.rs"

[lints.rust]
unsafe_code = "forbid"

[dependencies]
clap = { version = "~4.4", features = ["derive", "env"] }
color-eyre = { version = "0.6.2", default-features = false }
console = "~0.15"
dialoguer = "0.11.0"
eyre = "0.6.8"
indicatif = { version = "0.17.7", features = ["rayon"] }
itertools = "0.12.0"
modinfo_7dtd = "0.1.1"
pad = "0.1.6"
rand = "0.8.5"
rayon = "1.8.0"
thiserror = "1.0.50"
