[package]
name = "modlet_7dtd"
version = "0.1.0"
edition = "2021"

[lib]
name = "modlet"
crate-type = ["lib"]

[dependencies]
eyre = { workspace = true }
glob = { workspace = true }
modinfo = { workspace = true }
quick-xml = { workspace = true }
